spring.application.name=Spring-Ai-tutorials
server.port=8080

spring.ai.chat.client.enabled= false

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.options.model=codellama:7b
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.chat.options.num-predict=300
